#指定环境
spring:
  profiles:
    active: dev
  #公共配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookinfo
    username: root
    password: cxw534721wf.
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: tbl_
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
      id-type: auto

#---
##生产环境
#server:
#  port: 80
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      table-prefix: tbl_
#      logic-delete-field: deleted
#      logic-not-delete-value: 0
#      logic-delete-value: 1
#      id-type: auto
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/bookinfo
#    username: root
#    password: cxw534721wf.
#  profiles: pro
#
#---
##开发环境
#server:
#  port: 81
#spring:
#  profiles: dev
#---
##测试环境
#server:
#  port: 82
#spring:
#  profiles: test